FROM python:3.8.1-alpine
RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

ENTRYPOINT [ "python", "src/secondary.py"]
CMD ["-f", "8001", "-g", "50001"]