FROM python:3.8.1-alpine
RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

ENTRYPOINT [ "python", "src/main.py"]
CMD ["-f", "8000", "-s", "0.0.0.0:50001"]